### ISSUE TITLE
Fan control not working after shutdown 

### ISSUE THREAD

**Issue by joelmathewthomas** [nbfc-linux/nbfc-linux#101]
**Context**
I have been using Arch Linux for a long time now, but one thing i haven't been able to do was fan control. Upon boot my system fans are at the lowest. For gaming , this is not ideal. Up until yesterday my usual workaround was to boot into windows , set fan speed to max using Nitrosense, and restart to Linux. So with `nbfc-linux`, and with the config for Acer Predator G3-572, i was able to control my fans. But the issue is that once i shutdown, i would not be able to do it. Then i would have to reboot to windows again and then reboot to Linux and then i can control it until the next shutdown.Basically , for me to be able to control my fans on Linux, I would have to boot to windows and then restart it to Linux.

**Describe the Bug**
Fan control not working until booted to windows and starting Nitrosense and then restarting into Linux.

**To Reproduce**
Install `nbfc-linux`.
Find a working config.`
Shutdown.
Boot directly into Linux.

**Expected behavior**
Fan control wont work until booting into windows and starting nitrosense and restarting into Linux.
**System information**
- Device Name : Acer Nitro 5 AN517-54
- NBFC config used : Acer Predator G3-572
 - Operating System: `Linux nitro5 6.4.11-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 19 Aug 2023 15:38:34 +0000 x86_64 GNU/Linux`
 - NBFC version : `nbfc-linux-0.1.7-3`

**Comment by kensad-ops** [comment]
try #65
