### ISSUE TITLE
Any way to run nbfc without having to use sudo?

### ISSUE THREAD

**Issue by PunkSamurai** [nbfc-linux/nbfc-linux#108]
I'm trying to make a simple widget to toggle between fan speed 100% and auto mode. Is there any ways i can run nbfc without sudo?

**Comment by BachoSeven** [comment]
You could add `/usr/bin/nbfc` to the list of programs which can be run as sudo without password in sudoers, for instance if you're in the group `wheel`:

```
## Allow members of group wheel to execute these commands without a password
%wheel ALL=(ALL) NOPASSWD: /usr/bin/nbfc
```
