### ISSUE TITLE
Can the same approach be used for controlling fans of proprietary desktop/workstations? (HP/Dell/Lenovo)

### ISSUE THREAD

**Issue by wrobelda** [nbfc-linux/nbfc-linux#110]
Hi there,

I am working with a HP Z2 G9 workstation desktop and, unfortunately, it comes with its own share of fan speed issues. Notably, it appears that the fan speed is tied to CPU usage — and not even to an average usage of all cores aggregated, but of a single core. I am running Proxmox VM on it and a single VM getting one or two cores busy will get the fans spinning like crazy. 

Do the EC probing and DSDT disassembly principles apply here as well? Has anyone actually managed to get in control of the dans on any of such workstations, be it HP, Dell or Lenovo?

I dumped the EC registers and it doesn't look like there's a lot going on here:
```
---|------------------------------------------------
   | 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
---|------------------------------------------------
00 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
10 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
20 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
30 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
40 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
50 | 00 00 00 00 00 87 05 00 00 00 00 00 02 00 00 00
60 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
70 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
80 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
90 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
A0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
B0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
C0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
D0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
F0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

I also dumped the DSDT and disassembled it, but before I get any further, is there even a point?

**Comment by braph** [comment]
No, this project cannot be used with desktop workstations.
