### ISSUE TITLE
(solved) install and run nbfc on sysvinit 

### ISSUE THREAD

**Issue by neonramzy** [nbfc-linux/nbfc-linux#116]
hi,I have successfully installed and run nbfc on Debian 12  and HP 8460p laptop and it solved the noisy fan problem.

 I want to know if it is possible to install and use nbfc on non systemd distributions? (like mx-linux or devuan)

 thanks for any help and info.

**Comment by braph** [comment]
I added a service file for System-V-Init. Try it out with:
`make PREFIX=/usr confdir=/etc INIT_SYSTEM=systemv && sudo make PREFIX=/usr confdir=/etc INIT_SYSTEM=systemv install`

Let me know if the service file can be improved.

Regards,

Benjamin

**Comment by neonramzy** [comment]
yes.
it works!
I just want to know this, does the nbfc service start automatically with the system or does it need another command?  Thanks.

**Comment by braph** [comment]
I'm not using a System-V system, but I googled it for you:

sudo update-rc.d nbfc_service defaults

should to the job

**Comment by neonramzy** [comment]
new install method dosent work any more. mx-linux 23.2
![Capture](https://github.com/nbfc-linux/nbfc-linux/assets/93700660/53360711-abd1-4f6a-b847-593303e0fa4b)

**Comment by braph** [comment]
You need to install the 'autoconf' package, which includes autoreconf

**Comment by neonramzy** [comment]
> You need to install the 'autoconf' package, which includes autoreconf

thank you,
installing "automake" and "autoconf" solved issue.

**Comment by BachoSeven** [comment]
Closing, 
since you edited it to `(solved)`
