### ISSUE TITLE
update or remove

### ISSUE THREAD

**Issue by neonramzy** [nbfc-linux/nbfc-linux#122]
If I have compiled and installed the nbfc manually, how can I update to newer release or remove it?
(debian)
thank you.

**Comment by braph** [comment]
First you have to know where you installed the previous version of nbfc-linux.

ls /usr/local/share/nbfc
ls /usr/share/nbfc

If the first command works, your --prefix is /usr/local,
if the second command works, your --prefix is /usr

For removing, clone the repository and do:

./autogen.sh && ./configure --prefix=YOUR_PREFIX --sysconfdir=/etc && make && sudo make uninstall

(replace YOUR_PREFIX with the right prefix that you found out before)

If you want to update, just do:

./autogen.sh && ./configure --prefix=YOUR_PREFIX --sysconfdir=/etc && make && sudo make install

Again, replace YOUR_PREFIX with the right prefix that you have found out before.

Regards,

Benjamin
