### ISSUE TITLE
Satellite L755 config files not work

### ISSUE THREAD

**Issue by oytunistrator** [nbfc-linux/nbfc-linux#124]
Copied this file [Toshiba Satellite L745.json](https://github.com/nbfc-linux/nbfc-linux/blob/main/share/nbfc/configs/Toshiba%20Satellite%20L745.json) to /etc/nbfc/nbfc.json but it not work:
```
 sudo nbfc_service
nbfc_service: INFO: Running version 0.1.15
nbfc_service: INFO: SYSCONFDIR is '/etc'
nbfc_service: INFO: DATADIR is '/usr/share'
nbfc_service: INFO: RUNSTATEDIR is '/run'
nbfc_service: ERROR: /etc/nbfc/nbfc.json: LegacyTemperatureThresholdsBehaviour: Unknown option

```

OS: Debian 12

**Comment by braph** [comment]
The model configuration files are not meant to be copied to /etc/nbfc/nbfc.json. If you want to set the Thosiba model configuration file, do the following:

sudo rm /etc/nbfc/nbfc.json # remove the old file
sudo nbfc config -s "Toshiba Satellite L745" # set the toshiba satellite model configuration file in /etc/nbfc/nbfc.json
sudo nbfc start # start the service

**Comment by oytunistrator** [comment]
Thanks. I fixed.
