### ISSUE TITLE
Better install instructions

### ISSUE THREAD

**Issue by StellarHarbour** [nbfc-linux/nbfc-linux#126]
Can you make better install instructions? I have Nobara Linux (Fedora underhood) and I could understand what to do at all, and when I'm trying to install [copr](https://copr.fedorainfracloud.org/coprs/trixieua/nbfc-linux/) 
It says Error: Unable to find a match: nbfc-linux

**Comment by braph** [comment]
Now there are DEBs and RPMs available, have a look under releases.
