### ISSUE TITLE
Error during installation - "configure: error: cannot run /bin/bash/..."

### ISSUE THREAD

**Issue by lien15305** [nbfc-linux/nbfc-linux#127]
"configure: error: cannot run /bin/bash/ ./config.sub" when I run
`./autogen.sh && ./configure --prefix=/usr --sysconfdir=/etc && make && sudo make install`

Would you know how to get around this? Installing on debian.

Thanks!

**Comment by braph** [comment]
Can you please provide the full output of ./configure?

**Comment by lien15305** [comment]
Managed to get it working with:
`git clone https://github.com/nbfc-linux/nbfc-linux.git`
`cd nbfc-linux/ && make && sudo make install`
All good now!
