### ISSUE TITLE
KBD Backlight Turns off

### ISSUE THREAD

**Issue by ecnivs** [nbfc-linux/nbfc-linux#134]
I'm on Acer Nitro An515-58 and my keyboard backlight turns off as soon as I start Nbfc service and remains that way till i turn it off

**Comment by braph** [comment]
You can try to disable the nbfc-service, turn off your device, remove the batttery pack and press the power button (to drain off the remaining power in your device). This helped me when I misconfigured my embedded controller.

Also: Can you please test if this problem persists when using the original NBFC software? https://github.com/UraniumDonut/nbfc-revive

**Comment by ecnivs** [comment]
Is there any way to run NBFC service without having my keyboard backlight turned off

**Comment by BachoSeven** [comment]
@ecnivs also have a look at https://github.com/nbfc-linux/nbfc-linux/issues/65, where the initial configuration for this line of laptops was initially discussed. Depending on the specific model, you might have to tweak the configuration.

**Comment by ecnivs** [comment]
Works Now!
