### ISSUE TITLE
Bug report for set behavior

### ISSUE THREAD

**Issue by arthurbg951** [nbfc-linux/nbfc-linux#137]
sudo nbfc start

nbfc_service: INFO: Running version 0.1.15
nbfc_service: INFO: SYSCONFDIR is '/etc'
nbfc_service: INFO: DATADIR is '/usr/share'
nbfc_service: INFO: RUNSTATEDIR is '/run'
nbfc_service: INFO: Using 'Acer Nitro AN515-51' as model config
modprobe: FATAL: Module ec_sys not found in directory /lib/modules/6.7.11-200.fc39.x86_64
nbfc_service: INFO: Using 'acpi_ec' as EmbeddedControllerType
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp1_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp2_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp3_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp4_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp5_input' as temperature source

sudo nbfc set -s 100

nbfc: INFO: Killing nbfc_service (11406)
nbfc_service: INFO: Running version 0.1.15
nbfc_service: INFO: SYSCONFDIR is '/etc'
nbfc_service: INFO: DATADIR is '/usr/share'
nbfc_service: INFO: RUNSTATEDIR is '/run'
nbfc_service: INFO: Using 'Acer Nitro AN515-51' as model config
modprobe: FATAL: Module ec_sys not found in directory /lib/modules/6.7.11-200.fc39.x86_64
nbfc_service: INFO: Using 'acpi_ec' as EmbeddedControllerType
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp1_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp2_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp3_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp4_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp5_input' as temperature source

sudo nbfc set -a

nbfc: INFO: Killing nbfc_service (11420)
nbfc_service: INFO: Running version 0.1.15
nbfc_service: INFO: SYSCONFDIR is '/etc'
nbfc_service: INFO: DATADIR is '/usr/share'
nbfc_service: INFO: RUNSTATEDIR is '/run'
nbfc_service: INFO: Using 'Acer Nitro AN515-51' as model config
modprobe: FATAL: Module ec_sys not found in directory /lib/modules/6.7.11-200.fc39.x86_64
nbfc_service: INFO: Using 'acpi_ec' as EmbeddedControllerType
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp1_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp2_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp3_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp4_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon3/temp5_input' as temperature source

sudo nbfc status

Read-only                : false
Selected Config Name     : Acer Nitro AN515-51
Temperature              : 45.80

Fan Display Name         : CPU fan
Auto Control Enabled     : true
Critical Mode Enabled    : false
Current Fan Speed        : 100.00
Target Fan Speed         : 0.00
Fan Speed Steps          : 6122

Fan Display Name         : GPU fan
Auto Control Enabled     : true
Critical Mode Enabled    : false
Current Fan Speed        : 100.00
Target Fan Speed         : 0.00
Fan Speed Steps          : 6122

**Comment by braph** [comment]
This problem isn't caused by `nbfc set`. I cannot say what's wrong. What I can see is that the `TargetFanSpeed` is set properly. If `CurrentFanSpeed` and `TargetFanSpeed` differ by more than 15%, the `RegisterWriteConfigurations` are set again:

```
    bool re_init_required = false;
    for_each_array(Fan*, f, fans) {
      e = Fan_UpdateCurrentSpeed(f);
      if (e)
        goto error;

      // Re-init if current fan speeds are off by more than 15%
      if (fabs(Fan_GetCurrentSpeed(f) - Fan_GetTargetSpeed(f)) > 15) {
        re_init_required = true;

        if (options.debug)
          Log_Debug("re_init_required = 1;\n");
      }
    }
```

Sorry, I cannot help you with this problem.

**Comment by arthurbg951** [comment]
I thought that this error could be incurred by an update. I just have uninstalled then reinstalled then the error seems to be gone...
