### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by RishiVora** [nbfc-linux/nbfc-linux#146]
`nbfc_service` is running as you can see

```
[rishi@nixos:~]$ sudo nbfc start
nbfc: INFO: Service already running (pid: 72024)
````

but I can't perform any functions

```
[rishi@nixos:~]$ sudo nbfc status -s
nbfc: ERROR: connect(): Connection refused

[rishi@nixos:~]$ sudo nbfc set -a
nbfc: ERROR: connect(): Connection refused
```

**Comment by braph** [comment]
Can you please stop the service with `sudo nbfc stop` and start it manually using `sudo nbfc_service` and give me the output? Also it would be good to know under which environment you are running NBFC.

**Comment by RishiVora** [comment]
I did that but while running `sudo nbfc_service`, I got

```
nbfc_service: INFO: Running version 0.2.3
nbfc_service: INFO: SYSCONFDIR is '/nix/store/xgmnl93zklzhd5pnx7gsvlzsks7abv6p-nbfc-linux/etc'
nbfc_service: INFO: DATADIR is '/nix/store/xgmnl93zklzhd5pnx7gsvlzsks7abv6p-nbfc-linux/share'
nbfc_service: INFO: RUNSTATEDIR is '/run'
nbfc_service: ERROR: /nix/store/xgmnl93zklzhd5pnx7gsvlzsks7abv6p-nbfc-linux/etc/nbfc/nbfc.json: No such file or directory
```

so I did

```
[rishi@nixos:~]$ sudo nbfc_service -c ~/.config/nbfc.json
nbfc_service: INFO: Running version 0.2.3
nbfc_service: INFO: SYSCONFDIR is '/nix/store/xgmnl93zklzhd5pnx7gsvlzsks7abv6p-nbfc-linux/etc'
nbfc_service: INFO: DATADIR is '/nix/store/xgmnl93zklzhd5pnx7gsvlzsks7abv6p-nbfc-linux/share'
nbfc_service: INFO: RUNSTATEDIR is '/run'
nbfc_service: INFO: Using 'ASUS VivoBook X505ZA_X505ZA' as model config
nbfc_service: INFO: Using 'ec_sys' as EmbeddedControllerType
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon5/temp0_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon5/temp1_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon5/temp2_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon5/temp3_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon5/temp4_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon5/temp5_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon5/temp6_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon5/temp7_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon5/temp8_input' as temperature source
nbfc_service: INFO: Using '/sys/class/hwmon/hwmon5/temp9_input' as temperature source
nbfc_service: INFO: Connected on port 6431
```
for the config, I used `ASUS VivoBook X505ZA_X505ZA` because auto did not find anything for my device and this was among the recommended 

```
[rishi@nixos:~]$ sudo nbfc config -r
ASUS VivoBook X505ZA_X505ZA
Asus Vivobook R540U
Asus Vivobook S400CA
```

As for the environment, I am running nixos unstable branch with flakes. My device is

```
[rishi@nixos:~]$ sudo nbfc get-model-name
ASUSTeK COMPUTER INC. VivoBook_ASUSLaptop K3402ZA_S3402ZA
```

I hope I gave all details you asked for.

**Comment by braph** [comment]
I updated NBFC-Linux to use Unix Domain Sockets instead of TCP/IP. You can check out version 0.2.4, install it and try it again.

**Comment by RishiVora** [comment]
okay, I did that and the particular error is resolved but now I get

```
[rishi@nixos:~]$ sudo nbfc set -s 90
nbfc: ERROR: Service returned: /nix/store/baqb9lcx5py9p1ybv4gb1w6yiwmn1d3y-nbfc-linux/etc/nbfc/nbfc.json: Read-only file system
```

even if i start it manually using `sudo nbfc_service -c ~/.config/nbfc.json`. but here is the strange part, check this status

```
[rishi@nixos:~]$ sudo nbfc status -a
Read-only                : false
Selected Config Name     : ASUS VivoBook  X505ZA_X505ZA
Temperature              : 42.44

Fan Display Name         : FAN1
Auto Control Enabled     : false
Critical Mode Enabled    : false
Current Fan Speed        : 87.50
Target Fan Speed         : 90.00
Fan Speed Steps          : 8
```

and now I try to set it to 40

```
[rishi@nixos:~]$ sudo nbfc set -s 40
nbfc: ERROR: Service returned: /nix/store/baqb9lcx5py9p1ybv4gb1w6yiwmn1d3y-nbfc-linux/etc/nbfc/nbfc.json: Read-only file system

[rishi@nixos:~]$ sudo nbfc status -a
Read-only                : false
Selected Config Name     : ASUS VivoBook  X505ZA_X505ZA
Temperature              : 43.96

Fan Display Name         : FAN1
Auto Control Enabled     : false
Critical Mode Enabled    : false
Current Fan Speed        : 37.50
Target Fan Speed         : 40.00
Fan Speed Steps          : 8
```

the status kinda reflects the changes despite the error, but I don't notice any difference in the fan speed physically. I mean my fan is pretty loud at 90% usually.

**Comment by braph** [comment]
I updated to version 0.2.5 now.

`nbfc: ERROR: Service returned: /nix/store/baqb9lcx5py9p1ybv4gb1w6yiwmn1d3y-nbfc-linux/etc/nbfc/nbfc.json: Read-only file system`

This has been an error, because nbfc_service didn't write to the right config file that has been passed with -c. This is now fixed.

Let me know if it works for you.

**Comment by braph** [comment]
Btw, you don't need `sudo` for `nbfc status` and `nbfc set`. (This is a new feature)

**Comment by RishiVora** [comment]
ohh, the error is no more. thats good. but the `nbfc set` does not seem to work. it does write to the specified config at `~/.config/nbfc.json` but the fan speed does not seem to change.

**Comment by braph** [comment]
> but the fan speed does not seem to change

That is probably because the selected model configuration doesn't match your laptop. Just because the config file partially matches your laptop model doesn't mean that it must work. Sorry.

**Comment by RishiVora** [comment]
aah, bummer. anything that I can do on my end like make a new custom config for my device or something?

**Comment by braph** [comment]
In theory, yes, you can create a new configuration file for your model. But it is very hard to figure out the right registers to read and write from. You can have a look at https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config for more information.

**Comment by RishiVora** [comment]
damn. I'll give that a shot. Thank you very much tho!! 😊

**Comment by RishiVora** [comment]
I was able to figure out the registers by probing the EC and plotting it. But setting the value using `ec_probe` didn't do anything. I dumped the registers but the changed value did not reflect.
