### ISSUE TITLE
Build fails on NixOS

### ISSUE THREAD

**Issue by abdlrhman08** [nbfc-linux/nbfc-linux#153]
Installing nbfc using flakes on NixOS fails in the build phase due to the following error
```
       > gcc -DNDEBUG -DSYSCONFDIR=\"/nix/store/fflyk6rnx9drkfah17fg7wgg6aflkjd4-nbfc-linux/etc\" -DDATADIR=\"/nix/store/fflyk6rnx9drkfah17fg7wgg6aflkjd4-nbfc-linux/share\" -DRUNSTATEDIR=\"/run\" -DVERSION=\"0.2.8\" -Wall -Os -flto src/test_model_config.c -o src/test_model_config -lm -s
       > (cd ./nbfc-gui; ./include_files.py qt.py > nbfc-qt.py)
       > /nix/store/226mxicx2n7hgdf2424vz5y526nlyly8-bash-5.2-p15/bin/bash: line 1: ./include_files.py: cannot execute: required file not found
       > make: *** [Makefile:58: nbfc-gui/nbfc-qt.py] Error 127

```

I've fixed it in my fork in abdlrhman08/nbfc-linux@8b16f70ec396b36631b3ce66f7301309f328ec05 by running `include_files,py` with python3 and adding python3 to `nativeBuildInputs` in `flake.nix`

**Comment by braph** [comment]
Hello,

could you try to change the shebang of `nbfc-gui/include_files.py` from `#!/usr/bin/python3` to `#!/usr/bin/env python3` and tell me if that fixes the problem as well?

Thank you!

Regards,

Benjamin

**Comment by abdlrhman08** [comment]
Hey @braph,

Yes it still fails

**Comment by k3yss** [comment]
@abdlrhman08 Can you make a PR to fix this?

**Comment by abdlrhman08** [comment]
@k3yss, Happily did that in #157. I don't know if this is the best way to go but we can discuss it in the PR
