### ISSUE TITLE
Current Latest Tag (0.2.7) does not work when built wih clang+musl

### ISSUE THREAD

**Issue by Sid127** [nbfc-linux/nbfc-linux#155]
I'm using a non-glibc distro (Chimera Linux), and the current release (v0.2.7) does not work properly on it. The distro uses musl as its libc and clang as its default compiler.

The service is started correctly, but using the `nbfc` client to do anything results in `ERROR: Empty response` the first time, following which all other uses result in `ERROR: Connection refused`

**Comment by Sid127** [comment]
Update: fixed with the following LDFLAGS  `-Wl -z stack-size=0x200000`

**Comment by nekopsykose** [comment]
it crashes because nbfc_service spawns a thread for every connection and then parses the json in that thread with the default stack size (which is 128K on musl) using a recursive parser (that eats the stack pretty easily) so it overflows and segfaults

**Comment by braph** [comment]
I changed the source code to be compatible with clang+musl.
