### ISSUE TITLE
how to list fan sensor for an unknown laptop model?

### ISSUE THREAD

**Issue by tribbloid** [nbfc-linux/nbfc-linux#169]
```
peng@pop-os:~$ nbfc get-model-name 
ASUSTeK COMPUTER INC. Vivobook_ASUSLaptop M5402RA_M5402RA
peng@pop-os:~$ sudo nbfc config --set auto
nbfc: ERROR: No recommended config found to apply automatically
```

to manually generate a config file, I need to list fan sensor & controller, unfortunately none of the command can give that information

**Comment by braph** [comment]
Hello! Sorry for replying so late. To get a list of all available configuration files, run `nbfc config --list`. I did that for you and there seems to be no configuration available for your laptop model, I'm sorry.
