### ISSUE TITLE
attribute 'packages' missing

### ISSUE THREAD

**Issue by dosedaf** [nbfc-linux/nbfc-linux#171]
`at /nix/store/n2g92gqwa0pdh7g92xydgjbjw6w8c0y1-source/nixos/nbfc.nix:18:17:
           17|     #  script = "${inputs.nbfc-linux.packages.x86_64-linux.default}/${command}";
           18|     script = "${pkgs.nbfc-linux.packages}/${command}";
             |                 ^
           19|
           `
           
but when i change it into pkgs.nbfc-linux, the service won't start

`× nbfc_service.service - NoteBook FanControl service
     Loaded: loaded (/etc/systemd/system/nbfc_service.service; enabled; preset: ignored)
     Active: failed (Result: exit-code) since Sun 2024-11-17 09:14:19 WIB; 427ms ago
   Duration: 19ms
 Invocation: 07a5ddefc75749c6b5a5c250db92561f
    Process: 102233 ExecStart=/nix/store/izjznfg97kgxpvb8a4kzx9rdn0kfdh1s-unit-script-nbfc_service-start/bin/nbfc_service-start (code=exited, status=3)
   Main PID: 102233 (code=exited, status=3)
         IP: 0B in, 0B out
   Mem peak: 2M
        CPU: 4ms

Nov 17 09:14:19 dosed systemd[1]: Started NoteBook FanControl service.
Nov 17 09:14:19 dosed nbfc_service-start[102234]: nbfc_service: INFO: Running version 0.2.7
Nov 17 09:14:19 dosed nbfc_service-start[102234]: nbfc_service: INFO: SYSCONFDIR is '/nix/store/w562k7y4j80yy9f6n3xs61dnk9knps5v-nbfc-linux-0.2.7/etc'
Nov 17 09:14:19 dosed nbfc_service-start[102234]: nbfc_service: INFO: DATADIR is '/nix/store/w562k7y4j80yy9f6n3xs61dnk9knps5v-nbfc-linux-0.2.7/share'
Nov 17 09:14:19 dosed nbfc_service-start[102234]: nbfc_service: INFO: RUNSTATEDIR is '/run'
Nov 17 09:14:19 dosed nbfc_service-start[102234]: nbfc_service: ERROR: /home/yoda/.config/nbfc.json: No such file or directory
Nov 17 09:14:19 dosed systemd[1]: nbfc_service.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Nov 17 09:14:19 dosed systemd[1]: nbfc_service.service: Failed with result 'exit-code'.
warning: error(s) occurred while switching to the new configuration`

**Comment by Raphael-08** [comment]
how did ya solve this i got the same!

**Comment by dosedaf** [comment]
I realized the issue was because I hadn’t created the nbfc.json file. To fix this, simply create an nbfc.json file in /home/user/.config and add the following line:

`
{
  "SelectedConfigId": "Acer Nitro AN515-58"
}
`
Make sure to replace "Acer Nitro AN515-58" with your notebook model.

If you're looking for a reproducible solution, you can refer to my nbfc.nix configuration here:
[nbfc.nix on GitHub](https://github.com/dosedaf/nix/blob/main/nixos/nbfc.nix)

There might be a better solution, but this works perfectly fine, so I’m sticking with it for now.

**Comment by Raphael-08** [comment]
> I realized the issue was because I hadn’t created the nbfc.json file. To fix this, simply create an nbfc.json file in /home/user/.config and add the following line:
> 
> `{ "SelectedConfigId": "Acer Nitro AN515-58" }` Make sure to replace "Acer Nitro AN515-58" with your notebook model.
> 
> If you're looking for a reproducible solution, you can refer to my nbfc.nix configuration here: [nbfc.nix on GitHub](https://github.com/dosedaf/nix/blob/main/nixos/nbfc.nix)
> 
> There might be a better solution, but this works perfectly fine, so I’m sticking with it for now.

ty soo much!
