### ISSUE TITLE
Config File name Spaces

### ISSUE THREAD

**Issue by MikeSpeigle** [nbfc-linux/nbfc-linux#29]
It seems to me that the config files need to have the space in their names removed in order to be loaded. I could not get sudo nbfc config --set Asus ROG GL702VM to work unless I changed the name of the config to  Asus_ROG_GL702VM.

**Comment by braph** [comment]
You have to put the filename in quotes, config --set "Asus ROG GL702VM"

**Comment by MikeSpeigle** [comment]
Thank you I knew I must have been doing something wrong. The front page here only said  sudo nbfc config --set MODEL  so I didn't realize I needed the quotes. I deleted the _ and reloaded the config and it seems to have worked. 
sudo nbfc config --set "Asus ROG GL702VM"
sudo nbfc start
Using 'Asus ROG GL702VM' as model config
Using 'ECSysLinux' as EmbeddedControllerType
Using '/sys/class/hwmon/hwmon6/temp0_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp1_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp2_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp3_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp4_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp5_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp6_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp7_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp8_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp9_input' as temperature source
