### ISSUE TITLE
`ec_probe` does not respect `--embbeded-controller`

### ISSUE THREAD

**Issue by sabian2008** [nbfc-linux/nbfc-linux#37]
I'm trying to write some values to the EC directly via the included `ec_probe`. However it is always reporting that `ec_sys` is not loaded. This is expected for the default options, however the message is still present if I run
```
# ec_probe --embedded-controller=ec_linux dump
> modprobe: FATAL: Module ec_sys not found in directory /lib/modules/5.15.12-200.fc35.x86_64
> Could not load `ec_sys' kernel module
```

This seems like a bug in the `ec_probe` binary.

**Comment by braph** [comment]
Hello, you are right, ec_probe didn't respect the --embedded-controller option. This is now fixed. Thanks for your bug report and sorry for being so very late.
