### ISSUE TITLE
ec_sys module missing in my Linux Mint Debian Edition

### ISSUE THREAD

**Issue by ArnouldN** [nbfc-linux/nbfc-linux#4]
Hello,
I recently got an old HP DV6 laptop running on AMD Athlon QL-65 2 core processors. OK it is not up to current standards, but it is enough for me.
I want to use Linux Mint Debian Edition because I am fed up with all the upgrades coming in when I don't expect them on my Lubuntu 20.04. And I want to drop Ubuntu because they dropped 32 bit systems.
Now my LMDE runs on 4.19.0-17-amd64 kernel and they have not included the ec_sys module in the /lib/modules/ directory. I found this out after having compiled and installed nbfc-linux from the downloaded sources here : error missing ec_sys module.
So I took an ec_sys.ko module file from my other lubuntu system and copied it to the laptop. Of course, as is always the case with Linux, it is not that simple. Question : am I supposed to compile this module "off tree". Compiling a module "off tree" is a new concept to me which I just only discovered...
Thank you for your answer.
Arnould

**Comment by ArnouldN** [comment]
OK me again. Yesterday I was a bit angry when I discovered this new Linux nightmare : the necessity to compile kernel modules "off tree" when they were not included in the distribution that I want to use.

Question : as this small ec_sys seems so important to nbfc, why not include a good working version in the sources of nbfc, that would solve the problem, woudn't it ?

**Comment by ArnouldN** [comment]
I managed to compile the missing ec_sys module. It was unnecessarily complicated as is often the case with linux : I needed about 10 hours to understand and implement. Of course next time the kernel is upgraded, I will be able to do it 1/4 of an hour. 

The very good news : now nbfc-linux is working like a charm in my old HP DV6 with Athlon QL-65 processor.

If someone is interested I could write a tutorial in here, but only if needed, because compiling a kernel "out-of-tree" is not really the subject of nbfc-linux.

And yes : thank very much braph for this wonderful port of nbfc-linux running in a tiny fraction of the memory of the original nbfc !

**Comment by braph** [comment]
Hello.

NBFC Linux already comes with an own implementation of the ec_sys kernel module, called `ECLinux`. I changed the source to try both implementations, first the one depending on the kernel module, then the one depending on `/dev/port`. Maybe this saves you the work of recompiling the ec_sys module

**Comment by ArnouldN** [comment]
Hello,I had seen you comment about ECLinux vs. ec_sys ‎module in the readme file, but you also wrote that ec_sys is preferred, thus my adventure with compiling an off tree module... Again thank you.                                                                                                                                      Arnould (France)                                                                                                                                                                                                                                                                                                                                                                                                                   From: braphSent: dimanche 22 août 2021 12:27To: nbfc-linux/nbfc-linuxReply To: nbfc-linux/nbfc-linuxCc: ArnouldN; AuthorSubject: Re: [nbfc-linux/nbfc-linux] ec_sys module missing in my Linux Mint Debian Edition (#4)
Hello.
NBFC Linux already comes with an own implementation of the ec_sys kernel module, called ECLinux. I changed the source to try both implementations, first the one depending on the kernel module, then the one depending on /dev/port. Maybe this saves you the work of recompiling the ec_sys module

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/nbfc-linux/nbfc-linux/issues/4#issuecomment-903246725",
"url": "https://github.com/nbfc-linux/nbfc-linux/issues/4#issuecomment-903246725",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
