### ISSUE TITLE
Doesn't work on Nobara

### ISSUE THREAD

**Issue by CilekciGs** [nbfc-linux/nbfc-linux#40]
It Works fine in arch but it doesn't work on Nobara (Glorious Egroll's Fedora Fork)

Using 'HP Omen 15-dc00xxxx' as model config
Using 'ECSysLinux' as EmbeddedControllerType
modprobe: FATAL: Module ec_sys not found in directory /lib/modules/5.17.7-301.fsync.fc36.x86_64
Could not load `ec_sys' kernel module

**Comment by Phoenix-Starlight** [comment]
Because the module was never compiled in the first place. Gotta configure and compile your own build for that.

**Comment by BachoSeven** [comment]
@CilekciGs I would add that you can try using the alternative implementation, as described in

https://github.com/nbfc-linux/nbfc-linux#troubleshooting
