### ISSUE TITLE
Why the fanspeed doesn't slow down

### ISSUE THREAD

**Issue by cxOrz** [nbfc-linux/nbfc-linux#43]
It just increase, but doesn't slow down. 
Only way is restart the nbfc , and the speed turns to the target speed.
But why need to manually restart it ? 
![image](https://user-images.githubusercontent.com/32982052/170506817-b000806e-b21e-441b-ae5f-c9370edd8e71.png)

**Comment by nekotxs** [comment]
Same problem, but with Acer Nitro AN515-57
`$ nbfc status -a
Read-only               : False
Selected config name    : Acer Nitro AN715-51
Temperature             : 53.07

Fan display name        : CPU fan
Auto control enabled    : True
Critical mode enabled   : False
Current fan speed       : 59.03
Target fan speed        : 38.0
Fan speed steps         : 6122

Fan display name        : GPU fan
Auto control enabled    : True
Critical mode enabled   : False
Current fan speed       : 69.01
Target fan speed        : 30.0
Fan speed steps         : 6122`

**Comment by kabra4** [comment]
i have the same problem, but fan speed is not increasing to target as well. not cooling cpu

**Comment by nekotxs** [comment]
@cxOrz is it solved?

**Comment by cxOrz** [comment]
> @cxOrz is it solved?

Yes, actually this problem never appeared again since I switched to ArchLinux, following the archwiki installed correct graphics card driver.

I uses `linux-zen` kernel with `nvidia-dkms`.

**Comment by BachoSeven** [comment]
which distro were you on at the time of posting?

**Comment by cxOrz** [comment]
> which distro were you on at the time of posting?

manjaro, I guess it's the driver's problem.

**Comment by nekotxs** [comment]
i had this problem with arch, but probably that was driver's problem too.
