### ISSUE TITLE
unknown option , when trying to run nbfc_service

### ISSUE THREAD

**Issue by allaeddineomc** [nbfc-linux/nbfc-linux#54]
trying to run nbfc_service manually causes this error 
```
[root@zenbook ~]# '/var/home/edge/.local/bin/nbfc_service' -c '/var/home/edge/Asus Zenbook UX310UA.json' --embedded-controller=ec_linux

/var/home/edge/Asus Zenbook UX310UA.json: NotebookModel: Unknown option
```

**Comment by BachoSeven** [comment]
@allaeddineomc the `-c` option of `nbfc_service` is not intended for specific notebook models, but rather for an alternative nbfc.json` configuration file `/etc/nbfc/nbfc.json`, as described in `man nbfc_service`.

If you wish to apply a configuration for the UX310UA (which is already present in the shipped configurations), you need to 

- start `nbfc_service` with Systemd (`systemctl enable --now nbfc_service`)
- set your desired config with `nbfc config -a "Asus Zenbook UX310UAK`.

lmk if you encounter any other issues.

**Comment by allaeddineomc** [comment]
is there's any way to load a notebook config file into the service from a location other than the default one , i'm using an immutable file system distro (fedora silverblue) and installing nbfc-linux using  ``` make install ``` fails so i installed the files in the home directory and seemingly there is no way to point the service into an alternate directory , is there's anything that i can do ?

**Comment by BachoSeven** [comment]
How did `make install` fail?

**Comment by BachoSeven** [comment]
I'm not that familiar with your filesystem layout so I can't think of a good solution, and it does appear there are no flags which achieve your goal.

**Comment by BachoSeven** [comment]
It appears that on Silverblue you can still install packages if they are available through RPM (with `rpm-ostree install`), however `nbfc-linux` has not been packaged yet there. If you would like @allaeddineomc you could contribute by making such package (again, I have no experience with rpm or I would do it myself).

**Comment by allaeddineomc** [comment]
i will try to package an appimage since it's usable on more immutable distros such as "holo iso" and "open suse micro os", if that didn't turn out well i will try an rpm
