### ISSUE TITLE
ec_linux timer expired

### ISSUE THREAD

**Issue by sixunity** [nbfc-linux/nbfc-linux#60]
```
[name@fedora nbfc-linux-0.1.7]$ sudo nbfc start
Using 'Xiaomi Mi Book (TM1613, TM1703)' as model config
Using 'ECLinux' as EmbeddedControllerType
Using '/sys/class/hwmon/hwmon6/temp1_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp2_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp3_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp4_input' as temperature source
Using '/sys/class/hwmon/hwmon6/temp5_input' as temperature source
EC_Linux_WriteByte: Timer expired

```

cannot use ec_sys as i am on fedora and they just decided that people dont need that module or something
i tried make with EMBEDDED_CONTROLLER=acpi_ec but that doesnt seem to have fixed the issue, i do have acpi_ec installed

**Comment by sixunity** [comment]
after trying to keep my fans under control, i found out that the original nbfc version actually works on fedora, it takes quite a bit longer to set up, but actually works, and works well

**Comment by BachoSeven** [comment]
@sixunity glad you found a setup which works for you! 

Unfortunately, I don't know what caused your original issue; I'll close this for now.
