### ISSUE TITLE
Can't use this on NixOS

### ISSUE THREAD

**Issue by aminriqky** [nbfc-linux/nbfc-linux#61]
Already try it with `nix-env -if .` but nbfc_service must enable/start to use it so i have to install it manually with configuration.nix by reading .nix file in this repository, looks like it can't read nbfc.json because it's stored in nix store and not in usual way. so after i configured nbfc.conf with my laptop model:
`{"SelectedConfigId": "Acer Nitro AN515-51", "NotebookModel": "Acer Nitro AN515-51", "Author": "Chandradeep Dey (modified by satcom886)", "EcPollInterval": 3000, "ReadWriteWords": true, "CriticalTemperature": 90, "FanConfigurations": [{"ReadRegister": 19, "WriteRegister": 55, "MinSpeedValue": 0, "MaxSpeedValue": 100, "IndependentReadMinMaxValues": true, "MinSpeedValueRead": 0, "MaxSpeedValueRead": 6122, "ResetRequired": true, "FanSpeedResetValue": 50, "FanDisplayName": "CPU fan", "TemperatureThresholds": [{"UpThreshold": 55, "DownThreshold": 43, "FanSpeed": 0.000000}, {"UpThreshold": 60, "DownThreshold": 44, "FanSpeed": 30.000000}, {"UpThreshold": 65, "DownThreshold": 50, "FanSpeed": 45.000000}, {"UpThreshold": 70, "DownThreshold": 56, "FanSpeed": 50.000000}, {"UpThreshold": 80, "DownThreshold": 63, "FanSpeed": 65.000000}, {"UpThreshold": 85, "DownThreshold": 68, "FanSpeed": 75.000000}, {"UpThreshold": 90, "DownThreshold": 78, "FanSpeed": 100.000000}], "FanSpeedPercentageOverrides": []}, {"ReadRegister": 21, "WriteRegister": 58, "MinSpeedValue": 0, "MaxSpeedValue": 100, "IndependentReadMinMaxValues": true, "MinSpeedValueRead": 0, "MaxSpeedValueRead": 6122, "ResetRequired": true, "FanSpeedResetValue": 50, "FanDisplayName": "GPU fan", "TemperatureThresholds": [{"UpThreshold": 55, "DownThreshold": 43, "FanSpeed": 0.000000}, {"UpThreshold": 60, "DownThreshold": 44, "FanSpeed": 30.000000}, {"UpThreshold": 65, "DownThreshold": 50, "FanSpeed": 45.000000}, {"UpThreshold": 70, "DownThreshold": 56, "FanSpeed": 50.000000}, {"UpThreshold": 80, "DownThreshold": 63, "FanSpeed": 65.000000}, {"UpThreshold": 85, "DownThreshold": 68, "FanSpeed": 75.000000}, {"UpThreshold": 90, "DownThreshold": 78, "FanSpeed": 100.000000}], "FanSpeedPercentageOverrides": []}], "RegisterWriteConfigurations": [{"WriteMode": "Set", "WriteOccasion": "OnInitialization", "Register": 34, "Value": 12, "ResetRequired": true, "ResetValue": 4, "ResetWriteMode": "Set", "Description": "CPU fan manual mode"}, {"WriteMode": "Set", "WriteOccasion": "OnInitialization", "Register": 33, "Value": 48, "ResetRequired": true, "ResetValue": 16, "ResetWriteMode": "Set", "Description": "GPU fan manual mode"}, {"WriteMode": "Set", "WriteOccasion": "OnInitialization", "Register": 16, "Value": 0, "ResetRequired": true, "ResetValue": 1, "ResetWriteMode": "Set", "Description": "CoolBoost off"}]}`
This is the result if i start nbfc or enable the service even though i set it right:
`/etc/nbfc/nbfc.json: NotebookModel: Unknown option`

Full thread post on [Reddit](https://www.reddit.com/r/NixOS/comments/wvk8rb/fan_control_for_laptop_from_github/)

**Comment by BachoSeven** [comment]
@aminriqky Why did you manually write the `nbfc.conf` file? You should select the config automatically with

```
nbfc config -a "Acer Nitro AN515-51"
```

Since the config is already present in the package's itself, there is no need to store it in the configuration file.

**Comment by aminriqky** [comment]
@BachoSeven i already tried it last time, but it did not found my laptop config, already tried it with other config too, this is because nix is storing it like this for example `/nix/store/is476j7dp9ggy8rrqcmx68dpj21n3v0f-nbfc-linux/` and not in usual way, that is why it did not found the NotebookModel:
`/etc/nbfc/nbfc.json: NotebookModel: Unknown option`

**Comment by BachoSeven** [comment]
You might find a solution here:

https://github.com/nbfc-linux/nbfc-linux/blob/main/nixos-installation.md

Somebody contributed this not long ago documenting some workarounds on Nix, hope it helps.

**Comment by aminriqky** [comment]
ah thank you i haven't read that, i will close this issue now.
