### ISSUE TITLE
Unreasonable "validation" restrictions

### ISSUE THREAD

**Issue by sidorsett** [nbfc-linux/nbfc-linux#66]
Hi,

Some of the existing validations are unjustified and artificially limit usage scenarios. I can create a pull request, but I would like to reach a consensus first.

1. `UpThreshold` may not be `0`: [code](https://github.com/nbfc-linux/nbfc-linux/blob/f94348e3c4becd2e0c7538e668656beeeca54ba4/src/model_config.c#L220)
The error message references differences to the original NBFC. Probably, it refers to [this paragraph](https://github.com/nbfc-linux/nbfc-linux/blob/0396c35b2afc02a705bb53c2fadb7b4f54915d97/README.md?plain=1#L76). However, the method doesn't prevent you from having `UpThreshold` of `0`. `0` has no special meaning in this context. 
Additionally, the error message suggests that `UpThreshold` must be greater than `0`, while the code actually compares against `0`, and because `UpThreshold` is defined as `short`, it may be set to a negative.
Finally, from application point of view, one can set up thresholds for negative temperatures. Imagine an enthusiast or a scientist. Even if not a typical use case, there is just no point to artificially restrict it.

2. Thresholds must be defined for the minimum fan speed: [code](https://github.com/nbfc-linux/nbfc-linux/blob/f94348e3c4becd2e0c7538e668656beeeca54ba4/src/model_config.c#L236)
It may be a totally valid and a desired profile that makes fan to never stop.

3. Thresholds must be defined for the maximum fan speed: [code](https://github.com/nbfc-linux/nbfc-linux/blob/f94348e3c4becd2e0c7538e668656beeeca54ba4/src/model_config.c#L241)
There is already the `CriticalTemperature` threshold that sets the fan to its maximum speed. It may be a totally valid and a desired profile that doesn't define thresholds for the maximum fan speed, but relies on the `CriticalTemperature` instead.

I look forward to your comments.

Cheers!

**Comment by braph** [comment]
Hello,

First of all, I want to apologize for my late response.

You are right on all points. I have adjusted the validation accordingly.

Thank you very much for pointing out these issues.

Best regards,

Benjamin Abendroth
