### ISSUE TITLE
Unable to change fan speed, and sensors don't show current speed

### ISSUE THREAD

**Issue by Leonardo-Cavalcante** [nbfc-linux/nbfc-linux#7]
Hey!
I am using Manjaro 21.1.1, and installed nbfc-linux through the AUR. I followed the steps on the readme.md to set it up, and chose the profile "Predator PH315-53".  However, the fans don't change the speed when i set them to 100% through the command `sudo nbfc set -s 100` .

The output of `sudo nbfc status -a` is :
```
Read-only               : False
Selected config name    : Acer Predator PH315-53
Temperature             : 31.71

Fan display name        : CPU fan (INTEL 10750H)
Auto control enabled    : False
Critical mode enabled   : False
Current fan speed       : 0.0
Target fan speed        : 100.0
Fan speed steps         : 0

Fan display name        : GPU fan (RTX 2060 Mobile)
Auto control enabled    : True
Critical mode enabled   : False
Current fan speed       : 0.0
Target fan speed        : 22.0
Fan speed steps         : 0
```

I tried changing the embedded controller to  ECLinux, but i get the following output:
`Invalid value for -e|--embedded-controller: ECLinux`

**Comment by braph** [comment]
Fixed the code and the readme: It's now ec_linux, not ECLinux. However, I have no idea what could be wrong with your setup, sorry.

**Comment by roth-a** [comment]
I have the same issue on a VivoBook_ASUSLaptop X509DA_D509DA

**Comment by BachoSeven** [comment]
Closing as the issue seems to be with using the wrong value of `--embedded-controller` for ECLinux
 (which is `ec_linux`)
