### ISSUE TITLE
Module ec_sys not found in directory /lib/modules/6.0.15-300.fc37.x86_64

### ISSUE THREAD

**Issue by arthurbg951** [nbfc-linux/nbfc-linux#72]
I was using nbfc-linux for somedays ago and it worked perfectly fine for me. But im using fedora 37 and windows 10 with dual boot. Today i was in linux and i've noticed the nbfc service is not working. I've tryed to use 'sudo nbfc start' and i got it:

Using 'Acer Nitro AN515-51' as model config
Using 'ECSysLinux' as EmbeddedControllerType
modprobe: FATAL: Module ec_sys not found in directory /lib/modules/6.0.15-300.fc37.x86_64
Could not load `ec_sys' kernel module

But i have ec_sys installed as [acpi_ec](https://github.com/musikid/acpi_ec) describe. This is what i get when i try to use 'sudo ./install.sh' from the project:

acpi_ec v1.0.2 is already installed

What should i do?

**Comment by BachoSeven** [comment]
Did you try rebooting to see if this was about an update to the kernel and relative modules?

**Comment by arthurbg951** [comment]
Yes..

**Comment by vivekkj123** [comment]
Same error here

**Comment by arthurbg951** [comment]
I found the solution to the problem. For some how with a update ec_sys was removed from compiled file.
The uninstall script finds it missing from the compiled file, but the install script (which can be used to reinstall) does not find the missing file. So the script returns that the program is installed.
Solution:
1. Use 'sudo ./uninstall.sh' from [acpi_ec](https://github.com/musikid/acpi_ec) command.
2. Use 'sudo ./install.sh' from [acpi_ec](https://github.com/musikid/acpi_ec) command.
3. Reboot pc.

**Comment by arthurbg951** [comment]
I've founded a solution. Check the post.

Cheers.
________________________________
De: Vivek K J ***@***.***>
Enviado: domingo, 1 de janeiro de 2023 06:57
Para: nbfc-linux/nbfc-linux ***@***.***>
Cc: Arthur Brito ***@***.***>; Author ***@***.***>
Assunto: Re: [nbfc-linux/nbfc-linux] Module ec_sys not found in directory /lib/modules/6.0.15-300.fc37.x86_64 (Issue #72)


Same error here
