### ISSUE TITLE
" EC_Linux_WriteByte: Timer expired " on Acer laptop

### ISSUE THREAD

**Issue by Chinmay1743** [nbfc-linux/nbfc-linux#76]
Hi,
When I try to run `nbfc_service`, I get the following error:

`sudo nbfc_service --embedded-controller=ec_linux`

`[sudo] password for [username]:` 

`Using 'Acer Aspire A715-42G' as model config`

`Using 'ECLinux' as EmbeddedControllerType`

`Using '/sys/class/hwmon/hwmon4/temp1_input' as temperature source`

`EC_Linux_WriteByte: Timer expired`

As you can see my laptop is Acer Aspire A715-42G

Hardware :
CPU : AMD Ryzen 5 5500U with Radeon Graphics (12) @ 2.100GHz
RAM : 32GB DDR4 SODiMM (16x2)
iGPU: AMD ATI 05:00.0 Lucienne
dGPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q
SSD : WD SN570

Software : 
OS        : Parrot OS 5.1 (Electro Ara) x86_64 (Debian, rolling release)
Kernel    : 6.0.0-2parrot1-amd64
Des. Env. : MATE 1.24.1

The module `ec_sys` is not available on Parrot OS so I installed `acpi_ec`

Note that config is not a problem. I can change it anytime. I use nbfc on windows and it works really well. I have a `.xml` config file on windows and I have converted the same to `.json` for linux. 

Installing other operating systems has always been painful since majority does not even get past the black screen with blinking cursor while live booting (Nvidia GPU issues) so changing the OS is not much of an option as I have tried Ubuntu, Pop-OS, Zorin, Manjaro, Debian. Manjaro worked but it made my laptop even hotter compared to Parrot and it was a bit buggy although Nvidia gave more options there (also, I prefer debian based distros over arch based so I decided to use Parrot as daily driver as it works for most use cases)

The output for `sensors` command (`lm-sensors`) is : 

k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +42.2°C  

amdgpu-pci-0500
Adapter: PCI adapter
vddgfx:      724.00 mV 
vddnb:       762.00 mV 
edge:         +39.0°C  
PPT:           0.00 W  

BAT1-acpi-0
Adapter: ACPI interface
in0:          12.96 V  
curr1:         1.66 A  

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +43.0°C  

nvme-pci-0200
Adapter: PCI adapter
Composite:    +37.9°C  (low  =  -5.2°C, high = +79.8°C)
                       (crit = +84.8°C)

nbfc_service has been successfully installed in linux, it is just not working. 
Previously, I was never able to see anything about fans in Linux when I tried to find about their information using other methods (not being aware that nbfc existed)

Any suggestions / help please ?

**Comment by Chinmay1743** [comment]
Additional information : I have to keep secure boot disabled all the time otherwise the system never shows grub at all and boots directly into windows10. It is a dual boot system.

**Comment by braph** [comment]
Hello,

If you want to run NBFC-Linux with acpi_ec module, you have to build it like this:

`make EMBEDDED_CONTROLLER=acpi_ec`

Maybe I will make it possible to use the acpi_ec module with a standard build in the future.

Note that the kernel module is only used by the `ec_sys_linux` controller, not the `ec_linux` controller.

If the problem persists the next step would be to enhance nbfc-linux as well as the original nbfc with more debugging information and have a look at what's different.

Please let me know if that information helped you.

**Comment by Chinmay1743** [comment]
Hi,
As I stated above "The module ec_sys is not available on Parrot OS so I installed acpi_ec", I found out during installation and research that `ec_sys` was removed for some reason from debian. 
Using `acpi_ec` helped me compile and make the program run at least, instead of recompiling kernel with ec_sys and potentially breaking the system.
I remember reading that acpi_ec should be used when Secure Boot is enabled but I have to keep it disabled so I really don't have much use for it. It is a bit weird overall.
Parrot core developers told me that ACPI implementation is different by manufacturers for Windows and Linux so that may be the case.
Is there any way I can run nbfc-linux in a way to get verbose output for every step that is happening? Maybe that can help?

**Comment by Chinmay1743** [comment]
I just ran the program again and got this output :
`$ nbfc_service --embedded-controller ec_sys_linux
Using 'Acer Aspire A715-42G' as model config
Using 'ECSysLinux' as EmbeddedControllerType
modprobe: FATAL: Module ec_sys not found in directory /lib/modules/6.0.0-12parrot1-amd64
Could not execute `modprobe ec_sys write_support=1'
`

Then I tried : 
`$ nbfc_service --embedded-controller ec_linux
Using 'Acer Aspire A715-42G' as model config
Using 'ECLinux' as EmbeddedControllerType
/dev/port: Permission denied
`

But with sudo : 
`$ sudo nbfc_service --embedded-controller ec_linux
[sudo] password for username: 
Using 'Acer Aspire A715-42G' as model config
Using 'ECLinux' as EmbeddedControllerType
Using '/sys/class/hwmon/hwmon4/temp1_input' as temperature source
EC_Linux_WriteByte: Timer expired
`

Back to square one.
