### ISSUE TITLE
Terminal appearance changes after running ec_probe dump

### ISSUE THREAD

**Issue by jwhendy** [nbfc-linux/nbfc-linux#8]
Not sure on the cause,  but something about the terminal formatting appears to glitch out urxvt for me. My font is changed in that terminal session afterward. Here's a new terminal, running a command, then `ec_probe dump` and another command. You can see the bold/gray font afterward.

![grab_2021-09-05_120613](https://user-images.githubusercontent.com/379357/132135332-79f04932-9b68-424a-affd-34aaf57ef557.png)

```
$ uname -a
Linux vera 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux

$ pacman -Q rxvt-unicode
rxvt-unicode 9.26-2

$ pacman -Q i3-gaps
i3-gaps 4.19.1-1
```

Any additional info I can provide?

**Comment by braph** [comment]
Fixed. Please tell me if it worked for you.

**Comment by jwhendy** [comment]
Fixed indeed. Excellent. Thanks for the quick work!
