### ISSUE TITLE
Specifying which temperatures to use for thresholds

### ISSUE THREAD

**Issue by jwhendy** [nbfc-linux/nbfc-linux#9]
Greetings,

I'm pretty new to nbfc and was looking into how temperature is assessed. In nbfc, nbfc-revive, and this project, it looks like they are averaged from the various `tempN_input` files, corresponding to `lm_sensors`. It looks like this might be done in two different places ([fs_sensors.c](https://github.com/nbfc-linux/nbfc-linux/blob/main/src/fs_sensors.c#L67) and [temperature_filter.c](https://github.com/nbfc-linux/nbfc-linux/blob/main/src/temperature_filter.c#L32)).

I noticed that the output of sensors can have some zones much higher than the output of `nbfc status`. For example, here's the output of `sensors` and `nbfc status -a` back to back:

```
$ sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +45.0°C  

pch_cometlake-virtual-0
Adapter: Virtual device
temp1:        +62.0°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          17.38 V  
curr1:         0.00 A  

nvme-pci-0200
Adapter: PCI adapter
Composite:    +44.9°C  (low  =  -5.2°C, high = +79.8°C)
                       (crit = +84.8°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +88.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +66.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +62.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +65.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +66.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +65.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +89.0°C  (high = +100.0°C, crit = +100.0°C)

nvme-pci-6f00
Adapter: PCI adapter
Composite:    +23.9°C  (low  = -273.1°C, high = +76.8°C)
                       (crit = +78.8°C)
Sensor 1:     +23.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +36.9°C  (low  = -273.1°C, high = +65261.8°C)

nvme-pci-0300
Adapter: PCI adapter
Composite:    +43.9°C  (low  = -273.1°C, high = +81.8°C)
                       (crit = +84.8°C)
Sensor 1:     +43.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +43.9°C  (low  = -273.1°C, high = +65261.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +28.0°C  (crit = +128.0°C)
temp2:        +53.0°C  (crit = +128.0°C)
temp3:        +55.0°C  (crit = +128.0°C)
temp4:        +52.0°C  (crit = +128.0°C)
temp5:        +34.0°C  (crit = +128.0°C)
temp6:        +40.0°C  (crit = +128.0°C)
temp7:        +41.0°C  (crit = +128.0°C)
temp8:        +46.0°C  (crit = +128.0°C)
temp9:         +0.0°C  (crit = +128.0°C)

$ nbfc status
Service enabled		: True
Read-only		: False
Selected config name	: HP ZBook Fury 15 G7
Temperature		: 70

Fan display name	: Right fan
Auto control enabled	: True
Critical mode enabled	: False
Current fan speed	: 72.94
Target fan speed	: 75.00
Fan speed steps		: 255

Fan display name	: Left Fan
Auto control enabled	: True
Critical mode enabled	: False
Current fan speed	: 72.94
Target fan speed	: 75.00
Fan speed steps		: 255
```

The average of the `coretemp-isa-0000` grouping is 71.6C, so I'm thinking this is similar to what `nbfc` is using. My preference would be to track the `Package id 0` temperature which tends to be much higher than the others. What do you think about allowing the user to specify options for this? For example, options could entail:

- max: take the max of temps listed in `/sys/class/hwmon/*`
- mean: take the average of these temps (current behavior)
- path: specify a single sensor file to track

**Comment by snowyoneill** [comment]
Seconding this. I'm also seeing under estimates of the overall cpu temperature. If i switch off nbfc and the laptop switches back to auto mode the fans ramp up for a while until the system temps have dropped.

There are a number of cpu temp sensors to choose from on my system, it would be nice to be able to point to one of those EC registers and poll the temps from there.

I would advise against using the 'max' of the cpu core temps as the input source given that if you running even a brief workload a single core temp might spike (resulting in nbfc spinning up the fans) even though the overall package temps are fine.

**Comment by braph** [comment]
Hello @jwhendy and @snowyoneill ,

First, I want to apologize for keeping you waiting for so long. I was going through a tough time when this issue was created. But now, I have found the time to address it.

I have implemented the requested feature. You can now choose between three different algorithms and have the option to specify the temperature sources.

See https://github.com/nbfc-linux/nbfc-linux?tab=readme-ov-file#advanced-configuration for more information.

Please let me know if the feature meets your expectations.

Best regards,

Benjamin Abendroth

**Comment by jwhendy** [comment]
No worries and thanks for the persistence/follow-up @braph ! I had to leave linux at work due to IT changes and am now on a Macbook, but hope this feature is useful to others. From skimming the new options, I like what you did even better than my past self's suggestion. Re-reading my own suggestion, I thought "hmm, even better would be to define the scope of _which_ sensors should be considered in the computations" and that's exactly what you did!

Many thanks and best to you.
