### ISSUE TITLE
how do i make a config?

### ISSUE THREAD

**Issue by PunkSamurai** [nbfc-linux/nbfc-linux#91]
I'm sorry if this has been asked before, but basically I want to make a configuration for my laptup, Acer Aspire A715-42G

Additionally, i want to try to make a plasma widget that can switch between max and auto fan control. Would something like this be feasible using NBFC?

Sorry if this wasn't the best place to ask questions but I was not sure how else to contact you guys

**Comment by PunkSamurai** [comment]
alright, really appreciate the help!

**Comment by PunkSamurai** [comment]
Okay so about that

I can set fan speed to max, but am unable to make it go back to auto.

Running nbfc status -a gives me:

```
Read-only                : false
Selected Config Name     : Acer Nitro AN715-51
Temperature              : 57.19

Fan Display Name         : CPU fan
Auto Control Enabled     : true
Critical Mode Enabled    : false
Current Fan Speed        : 94.23
Target Fan Speed         : 44.00
Fan Speed Steps          : 6122

Fan Display Name         : GPU fan
Auto Control Enabled     : true
Critical Mode Enabled    : false
Current Fan Speed        : 51.57
Target Fan Speed         : 38.00
Fan Speed Steps          : 6122
```

(I used  Acer Nitro AN715-51 config as it was pretty close to my laptop and it works for the most part)

Running sudo nbfc set --auto just gives:

```
ailed to kill nbfc_service process (31176): No such process
Using 'Acer Nitro AN715-51' as model config
Using 'ec_sys_linux' as EmbeddedControllerType
Using '/sys/class/hwmon/hwmon4/temp1_input' as temperature source
```

But the fan stays at max. Any idea on what i should try?

**Comment by braph** [comment]
For a short time there was a bug in the service code of NBFC-Linux which caused the program to write the wrong PID to the PID file. You can try to checkout the current version where this was fixed. Also do a "killall nbfc_service" to ensure that there are no other running instances of the service.

**Comment by PunkSamurai** [comment]
Sorry for not replying, had exams, and kind of left this on the back burner. 

Running `systemctl status nbfc_service` just gives:
```
 nbfc_service.service - NoteBook FanControl service
     Loaded: loaded (/lib/systemd/system/nbfc_service.service; disabled; preset: enabled)
     Active: inactive (dead)
```

I think running `killall nbfc_service` kills the processes, however the fan stays at whatever setting it was earlier. I can restart nbfc after that but no change to fan speed, can't get it back to auto. 

Also sorry if this is a dumb question but how do I update nbfc? Just download and build from scratch? Or can i just git pull or something like that?

**Comment by PunkSamurai** [comment]
Actually nevermind, after updating everything works great.

Only thing i need to now is if there's any way to run these without sudo, because I dont think exec allows us to run sudo commands just like that
