### ISSUE TITLE
nbfc_service file missing in src as per make file

### ISSUE THREAD

**Issue by BV-Pradeep** [nbfc-linux/nbfc-linux#99]
Trying to install NBFC linux on Acer Nitro Series Laptop by following this [medium [article](https://medium.com/@prabhatmaurya907/how-to-make-your-acer-nitro-5-linux-ready-2821ea23cd81) ].

After extracting and run make command following error pops up
![image](https://github.com/nbfc-linux/nbfc-linux/assets/16688720/38c39e08-94f3-4258-9c67-3db8465ef80b)

The error code corresponds to a missing file, I tried replacing nbfc_service with service in make file and running it again
![image](https://github.com/nbfc-linux/nbfc-linux/assets/16688720/a311e6f6-158d-4c63-9b8b-ac04ae8b271c)

Still No result.  How to resolve this issue

**Comment by braph** [comment]
You are missing a c-compiler. Install gcc and try it again

**Comment by BachoSeven** [comment]
@BV-Pradeep Looks like you're on Ubuntu; you can install the Gnu compiler with

```
sudo apt install build-essential

```

Let us know if you have any further issues, closing.
